global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "batch-worker"
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - type: A
        port: 80
        names:
          - "batch-worker"
